service: serverless10167
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  versionFunctions: false
  logs:
    frameworkLambda: true


functions:
  test:
    handler: index.handler
    provisionedConcurrency: 1
    events:
      - s3:
          bucket: !Ref Bucket
          existing: true

resources:
  Resources:
    Bucket:
      Type: AWS::S3::Bucket

